// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 28f3299f349ba0ff "Sense View Web App", do not edit manually */
"use client";
import {
  stdin_default
} from "./chunks/chunk-D65ZKCX7.js";
import "./chunks/chunk-57OI545D.js";
import "./chunks/chunk-LH24IRSJ.js";
import "./chunks/chunk-JZJDHDUF.js";
import "./chunks/chunk-6TLROV7Q.js";
import "./chunks/chunk-33IQSVUA.js";
import "./chunks/chunk-3EPZWXLT.js";
import "./chunks/chunk-ZA6GRI77.js";
import "./chunks/chunk-JBHZY42Q.js";
import "./chunks/chunk-GIW62UBX.js";
import "./chunks/chunk-4ARG4HPX.js";
import "./chunks/chunk-K5HAYHV7.js";
import "./chunks/chunk-55D774EJ.js";
import "./chunks/chunk-YPXXIIOI.js";
import "./chunks/chunk-SBVXWYNT.js";
import "./chunks/chunk-FUFDJHP4.js";
import "./chunks/chunk-ZC6P7TRE.js";
import "./chunks/chunk-IV6B2NPJ.js";
import "./chunks/chunk-BTSBQWPZ.js";

// virtual:content-panel
import { Fragment } from "react";
import { ContextProviders } from "unframer";
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
  "base": "wuusWzEdH",
  "md": "jFqOLgkwu"
};
stdin_default.Responsive = ({ locale, ...rest }) => {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: { "OJApodFFO": { "path": "/blog/:slug" }, "Pt3zunCXR": { "path": "/blog" }, "augiA20Il": { "path": "/" } },
      children: /* @__PURE__ */ jsx(
        WithFramerBreakpoints,
        {
          Component: stdin_default,
          variants: defaultResponsiveVariants,
          ...rest
        }
      ),
      framerSiteId: "28f3299f349ba0ffbaf4514e332ff2a5359687cd1069128f47d2d61a42e84f16",
      locale,
      locales
    }
  );
};
function ComponentWithRoot({ locale, ...rest }) {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: {
        "OJApodFFO": {
          "path": "/blog/:slug"
        },
        "Pt3zunCXR": {
          "path": "/blog"
        },
        "augiA20Il": {
          "path": "/"
        }
      },
      children: /* @__PURE__ */ jsx(stdin_default, { ...rest }),
      framerSiteId: "28f3299f349ba0ffbaf4514e332ff2a5359687cd1069128f47d2d61a42e84f16",
      locale,
      locales
    }
  );
}
Object.assign(ComponentWithRoot, stdin_default);
export {
  ComponentWithRoot as default
};
