/* This file was generated by Unframer, do not edit manually */
import * as React from "react"

import { UnframerBreakpoint } from "unframer"

type Locale = string
export interface Props {
    children?: React.ReactNode
    locale?: Locale
    style?: React.CSSProperties
    className?: string
    id?: string
    width?: any
    height?: any
    layoutId?: string
    "variant"?: 'Green' | 'Yellow' | 'Red' | 'Red 02' | 'Green TABLET' | 'Yellow TABLET' | 'Red TABLET' | 'Red 02 TABLET'
    "title"?: string
    "subdata"?: string
    "data"?: string
    "color"?: string
    "fontSize"?: number
    "fontSize2"?: number
    "info"?: string
}

const GaugeChartFramerComponent = (props: Props) => any

type VariantsMap = Partial<Record<UnframerBreakpoint, Props['variant']>> & { base: Props['variant'] }

GaugeChartFramerComponent.Responsive = (props: Omit<Props, 'variant'> & {variants?: VariantsMap}) => any

export default GaugeChartFramerComponent

