/* This file was generated by Unframer, do not edit manually */
import * as React from "react"

import { UnframerBreakpoint } from "unframer"

type Locale = string
export interface Props {
    children?: React.ReactNode
    locale?: Locale
    style?: React.CSSProperties
    className?: string
    id?: string
    width?: any
    height?: any
    layoutId?: string
    "variant"?: 'DESKTOP' | 'TABLET' | 'Variant 3' | 'Variant 4' | 'Variant 5' | 'NOGRAPHS'
    "text"?: string
    "title"?: string
    "info"?: string
    "date"?: string | Date
}

const LineChartFramerComponent = (props: Props) => any

type VariantsMap = Partial<Record<UnframerBreakpoint, Props['variant']>> & { base: Props['variant'] }

LineChartFramerComponent.Responsive = (props: Omit<Props, 'variant'> & {variants?: VariantsMap}) => any

export default LineChartFramerComponent

