// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 28f3299f349ba0ff "Sense View Web App", do not edit manually */
"use client";
import {
  stdin_default
} from "./chunks/chunk-YINY2Y2Q.js";
import "./chunks/chunk-DXLWIGY2.js";
import "./chunks/chunk-6CVX2UBA.js";
import "./chunks/chunk-J5MWRPNA.js";
import "./chunks/chunk-4ARG4HPX.js";
import "./chunks/chunk-K5HAYHV7.js";
import "./chunks/chunk-55D774EJ.js";
import "./chunks/chunk-YPXXIIOI.js";
import "./chunks/chunk-5FTUJNKV.js";
import "./chunks/chunk-BTSBQWPZ.js";

// virtual:options
import { Fragment } from "react";
import { ContextProviders } from "unframer";
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
  "base": "zTZvxrY0J",
  "md": "FWLiwfxJq"
};
stdin_default.Responsive = ({ locale, ...rest }) => {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: { "OJApodFFO": { "path": "/blog/:slug" }, "Pt3zunCXR": { "path": "/blog" }, "augiA20Il": { "path": "/" } },
      children: /* @__PURE__ */ jsx(
        WithFramerBreakpoints,
        {
          Component: stdin_default,
          variants: defaultResponsiveVariants,
          ...rest
        }
      ),
      framerSiteId: "28f3299f349ba0ffbaf4514e332ff2a5359687cd1069128f47d2d61a42e84f16",
      locale,
      locales
    }
  );
};
function ComponentWithRoot({ locale, ...rest }) {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: {
        "OJApodFFO": {
          "path": "/blog/:slug"
        },
        "Pt3zunCXR": {
          "path": "/blog"
        },
        "augiA20Il": {
          "path": "/"
        }
      },
      children: /* @__PURE__ */ jsx(stdin_default, { ...rest }),
      framerSiteId: "28f3299f349ba0ffbaf4514e332ff2a5359687cd1069128f47d2d61a42e84f16",
      locale,
      locales
    }
  );
}
Object.assign(ComponentWithRoot, stdin_default);
export {
  ComponentWithRoot as default
};
