/* This file was generated by Unframer, do not edit manually */
import * as React from "react"

import { UnframerBreakpoint } from "unframer"

type Locale = string
export interface Props {
    children?: React.ReactNode
    locale?: Locale
    style?: React.CSSProperties
    className?: string
    id?: string
    width?: any
    height?: any
    layoutId?: string
    "variant"?: 'DESKTOP' | 'DESKTOP DATOS' | 'DESKTOP ALERTAS' | 'TABLET' | 'PHONE' | 'TABLET DATOS' | 'TABLET ALERTAS' | 'PHONE DATOS' | 'PHONE ALERTAS' | 'NOGRAPHS' | 'NOGRAPHDATA' | 'NOGRAPHALERT'
}

const PanelFramerComponent = (props: Props) => any

type VariantsMap = Partial<Record<UnframerBreakpoint, Props['variant']>> & { base: Props['variant'] }

PanelFramerComponent.Responsive = (props: Omit<Props, 'variant'> & {variants?: VariantsMap}) => any

export default PanelFramerComponent

