// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 28f3299f349ba0ff "Sense View Web App", do not edit manually */
"use client";

// virtual:compress
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/aByUy2WEjGMRHNi2Yo2x/Phi1Q3drBc6vQMFzfYR2/KaLJqNYLD.js
import { jsx as _jsx } from "react/jsx-runtime";
import { addFonts, cx, SVG, useComponentViewport, useLocaleInfo, useVariantState, withCSS } from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var serializationHash = "framer-Bc9S2";
var variantClassNames = { T6vPv8eHT: "framer-v-1jbi2s2" };
var transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(() => ({ ...config, transition }), [JSON.stringify(transition)]);
  return /* @__PURE__ */ _jsx(MotionConfigContext.Provider, { value: contextValue, children });
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
  return { ...props };
};
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function(props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const { baseVariant, classNames, clearLoadingGesture, gestureHandlers, gestureVariant, isLoading, setGestureState, setVariant, variants } = useVariantState({ defaultVariant: "T6vPv8eHT", ref: refBinding, variant, variantClassNames });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /* @__PURE__ */ _jsx(LayoutGroup, { id: layoutId ?? defaultLayoutId, children: /* @__PURE__ */ _jsx(Variants, { animate: variants, initial: false, children: /* @__PURE__ */ _jsx(Transition, { value: transition1, children: /* @__PURE__ */ _jsx(motion.div, { ...restProps, ...gestureHandlers, className: cx(scopingClassNames, "framer-1jbi2s2", className, classNames), "data-framer-name": "Variant 1", layoutDependency, layoutId: "T6vPv8eHT", ref: refBinding, style: { ...style }, children: /* @__PURE__ */ _jsx(SVG, { className: "framer-1hatm38", "data-framer-name": "Compress", layout: "position", layoutDependency, layoutId: "kvwhvuxjp", opacity: 1, svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 25 25"><g transform="translate(5.2 1.27)" id="ss12849485636_1"><path d="M 0 12 L 0 11 L 14 11 L 14 12 Z M 0 9.23 L 0 8.23 L 14 8.23 L 14 9.23 Z M 6.5 20.23 L 6.5 16.107 L 4.4 18.207 L 3.692 17.499 L 7 14.192 L 10.308 17.499 L 9.6 18.207 L 7.5 16.119 L 7.5 20.23 Z M 7 6.038 L 3.692 2.73 L 4.4 2.022 L 6.5 4.122 L 6.5 0 L 7.5 0 L 7.5 4.123 L 9.6 2.023 L 10.308 2.731 Z" fill="var(--token-48c95b4e-44f6-4ac3-b044-c0cab34489dd, rgb(33, 33, 33)) /* {&quot;name&quot;:&quot;Text primary&quot;} */"></path></g></svg>', svgContentId: 12849485636, withExternalLayout: true }) }) }) }) });
});
var css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-Bc9S2.framer-17vrby6, .framer-Bc9S2 .framer-17vrby6 { display: block; }", ".framer-Bc9S2.framer-1jbi2s2 { height: 25px; overflow: hidden; position: relative; width: 25px; }", ".framer-Bc9S2 .framer-1hatm38 { flex: none; height: 25px; left: 0px; position: absolute; top: 0px; width: 25px; }"];
var FramerKaLJqNYLD = withCSS(Component, css, "framer-Bc9S2");
var stdin_default = FramerKaLJqNYLD;
FramerKaLJqNYLD.displayName = "Compress";
FramerKaLJqNYLD.defaultProps = { height: 25, width: 25 };
addFonts(FramerKaLJqNYLD, [{ explicitInter: true, fonts: [] }], { supportsExplicitInterCodegen: true });

// virtual:compress
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
stdin_default.Responsive = ({ locale, ...rest }) => {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: { "OJApodFFO": { "path": "/blog/:slug" }, "Pt3zunCXR": { "path": "/blog" }, "augiA20Il": { "path": "/" } },
      children: /* @__PURE__ */ jsx(
        WithFramerBreakpoints,
        {
          Component: stdin_default,
          variants: defaultResponsiveVariants,
          ...rest
        }
      ),
      framerSiteId: "28f3299f349ba0ffbaf4514e332ff2a5359687cd1069128f47d2d61a42e84f16",
      locale,
      locales
    }
  );
};
function ComponentWithRoot({ locale, ...rest }) {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: {
        "OJApodFFO": {
          "path": "/blog/:slug"
        },
        "Pt3zunCXR": {
          "path": "/blog"
        },
        "augiA20Il": {
          "path": "/"
        }
      },
      children: /* @__PURE__ */ jsx(stdin_default, { ...rest }),
      framerSiteId: "28f3299f349ba0ffbaf4514e332ff2a5359687cd1069128f47d2d61a42e84f16",
      locale,
      locales
    }
  );
}
Object.assign(ComponentWithRoot, stdin_default);
export {
  ComponentWithRoot as default
};
