// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 28f3299f349ba0ff "Sense View Web App", do not edit manually */
"use client";

// virtual:notifications
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/h6E64fdPDHyT8e8JKIWy/tCUzfOMNJkZ4d5K5Zp6Q/l_IcJWqLd.js
import { jsx as _jsx } from "react/jsx-runtime";
import { addFonts, cx, SVG, useComponentViewport, useLocaleInfo, useVariantState, withCSS } from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var serializationHash = "framer-nXHBO";
var variantClassNames = { cfNNQebJm: "framer-v-mznwee" };
var transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(() => ({ ...config, transition }), [JSON.stringify(transition)]);
  return /* @__PURE__ */ _jsx(MotionConfigContext.Provider, { value: contextValue, children });
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
  return { ...props };
};
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function(props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className, layoutId, variant, ...restProps } = getProps(props);
  const { baseVariant, classNames, clearLoadingGesture, gestureHandlers, gestureVariant, isLoading, setGestureState, setVariant, variants } = useVariantState({ defaultVariant: "cfNNQebJm", ref: refBinding, variant, variantClassNames });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /* @__PURE__ */ _jsx(LayoutGroup, { id: layoutId ?? defaultLayoutId, children: /* @__PURE__ */ _jsx(Variants, { animate: variants, initial: false, children: /* @__PURE__ */ _jsx(Transition, { value: transition1, children: /* @__PURE__ */ _jsx(motion.div, { ...restProps, ...gestureHandlers, className: cx(scopingClassNames, "framer-mznwee", className, classNames), "data-framer-name": "Variant 1", layoutDependency, layoutId: "cfNNQebJm", ref: refBinding, style: { ...style }, children: /* @__PURE__ */ _jsx(SVG, { className: "framer-4uq8o7", "data-framer-name": "Notifications", layout: "position", layoutDependency, layoutId: "h5lYpTKd_", opacity: 1, svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 41 40"><g transform="translate(8.533 5)" id="ss12762186509_1"><path d="M 0 26.282 L 0 24.615 L 2.693 24.615 L 2.693 11.41 C 2.693 9.233 3.382 7.318 4.76 5.665 C 6.138 4.012 7.885 2.983 10 2.577 L 10 1.667 C 10 1.204 10.162 0.81 10.485 0.487 C 10.793 0.169 11.22 -0.007 11.663 0 C 12.125 0 12.519 0.162 12.845 0.486 C 13.171 0.81 13.334 1.204 13.334 1.666 L 13.334 2.577 C 15.449 2.983 17.196 4.012 18.574 5.665 C 19.952 7.318 20.641 9.233 20.641 11.41 L 20.641 24.615 L 23.334 24.615 L 23.334 26.282 Z M 11.661 30.641 C 10.945 30.652 10.257 30.366 9.761 29.85 C 9.248 29.352 8.964 28.664 8.974 27.949 L 14.359 27.949 C 14.359 28.695 14.095 29.329 13.567 29.854 C 13.067 30.367 12.377 30.652 11.661 30.641 Z M 4.36 24.615 L 18.974 24.615 L 18.974 11.41 C 18.974 9.385 18.263 7.66 16.84 6.237 C 15.417 4.814 13.692 4.102 11.667 4.102 C 9.641 4.102 7.917 4.814 6.494 6.237 C 5.071 7.66 4.36 9.385 4.36 11.41 Z" fill="var(--token-48c95b4e-44f6-4ac3-b044-c0cab34489dd, rgb(33, 33, 33)) /* {&quot;name&quot;:&quot;Text primary&quot;} */"></path></g></svg>', svgContentId: 12762186509, withExternalLayout: true }) }) }) }) });
});
var css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-nXHBO.framer-z0yb2k, .framer-nXHBO .framer-z0yb2k { display: block; }", ".framer-nXHBO.framer-mznwee { cursor: pointer; height: 40px; overflow: hidden; position: relative; width: 41px; }", ".framer-nXHBO .framer-4uq8o7 { flex: none; height: 40px; left: 0px; position: absolute; top: 0px; width: 41px; }"];
var Framerl_IcJWqLd = withCSS(Component, css, "framer-nXHBO");
var stdin_default = Framerl_IcJWqLd;
Framerl_IcJWqLd.displayName = "Notifications";
Framerl_IcJWqLd.defaultProps = { height: 40, width: 41 };
addFonts(Framerl_IcJWqLd, [{ explicitInter: true, fonts: [] }], { supportsExplicitInterCodegen: true });

// virtual:notifications
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
stdin_default.Responsive = ({ locale, ...rest }) => {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: { "OJApodFFO": { "path": "/blog/:slug" }, "Pt3zunCXR": { "path": "/blog" }, "augiA20Il": { "path": "/" } },
      children: /* @__PURE__ */ jsx(
        WithFramerBreakpoints,
        {
          Component: stdin_default,
          variants: defaultResponsiveVariants,
          ...rest
        }
      ),
      framerSiteId: "28f3299f349ba0ffbaf4514e332ff2a5359687cd1069128f47d2d61a42e84f16",
      locale,
      locales
    }
  );
};
function ComponentWithRoot({ locale, ...rest }) {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: {
        "OJApodFFO": {
          "path": "/blog/:slug"
        },
        "Pt3zunCXR": {
          "path": "/blog"
        },
        "augiA20Il": {
          "path": "/"
        }
      },
      children: /* @__PURE__ */ jsx(stdin_default, { ...rest }),
      framerSiteId: "28f3299f349ba0ffbaf4514e332ff2a5359687cd1069128f47d2d61a42e84f16",
      locale,
      locales
    }
  );
}
Object.assign(ComponentWithRoot, stdin_default);
export {
  ComponentWithRoot as default
};
